import { escapeHtml } from "../html.js";
import type { SiteInfo } from "./header.js";

export function renderSiteFooter(siteInfo: SiteInfo): string {
  const builtAt = siteInfo.builtAt
    ? new Date(siteInfo.builtAt).toLocaleString("ja-JP", {
        year: "numeric",
        month: "2-digit",
        day: "2-digit",
        hour: "2-digit",
        minute: "2-digit",
      })
    : null;

  const timeHtml = builtAt
    ? `<span class="site-footer__time">${escapeHtml(builtAt)}</span>`
    : "";

  return `<footer class="site-footer">
      <div class="site-footer__inner">
        <span class="site-footer__text">Generated by Spekta</span>${timeHtml}
      </div>
    </footer>`;
}
